final List<List<String>> questionAnswer = [
    ["Who companion is known as 'Dhun-Noorayn'?", "Uthman ibn Affan (Ra)"],
    ["Which prophet was swallowed by a big fish?", "Yunus (As)"],
    ["Name a surah that has only 3 verses?", "Surah Al-Kawthar, An Nasr, Al A'sr"],
    ["What is the first word revealed in the Qur'an?", "Iqra (Read)"],
    ["Who was the first child to accept Islam?", "Ali ibn Abi Talib (Ra)"],
    ["Which prophet had a father and grandfather who were prophets?", "Yusuf (As) / Yaqub (As)"],
    ["Who is the last prophet in Islam?", "Muhammad (ﷺ)"],
    ["Which prophet is known for building the Ark?", "Nuh (As)"],
    ["Which prophet was thrown into the fire but was saved by Allah?", "Ibrahim (As)"],
    ["Who was the mother of Prophet Isa (As)?", "Maryam (As)"],
    ["Which prophet split the sea with Allah's permission?", "Musa (As)"],
    ["Which Surah is known as 'The Heart of the Qur'an'?", "Surah Yasin"],
    ["Who was the companion known as 'The Sword of Allah'?", "Khalid bin Walid (Ra)"],
    ["Which prophet interpreted the king's dream in Egypt?", "Yusuf (As)"],
    ["Which prophet is mentioned most frequently in the Qur'an?", "Musa (As)"],
    ["Who was the wife of Prophet Ibrahim (As)?", "Sarah (As)"],
    ["Which prophet prayed for the rain in drought?", "Nuh (As)"],
    ["Which Surah is named after a woman?", "Surah Maryam"],
    ["Who is the first prophet?", "Adam (As)"],
    ["Which companion was known for his knowledge and wisdom?", "Abu Hurairah (Ra)"],
    ["Who was the first martyr in Islam?", "Sumayyah bint Khayyat (Ra)"],
    ["Which prophet was known for his patience?", "Ayyub (As)"],
    ["Which prophet talked to ants?", "Sulaiman (As)"],
    ["Who is known as 'Al-Faruq' among the companions?", "Umar ibn Al-Khattab (Ra)"],
    ["Which prophet's story includes a well and a basket?", "Musa (As)"],
    ["In which month was the Battle of Badr fought?", "Ramadan"],
    ["Which Surah will come as a flock of birds on the Day of Qiyamah?", "Surah Al-Baqarah & Ali 'Imran"],
    ["Which angel has control over rain?", "Mika'il (As)"],
    ["Which prophet's nation fully accepted Islam?", "Yunus (AS)"],
    ["On which month is Eid ul-Fitr?", "Shawwal"],
    ["Who built a barrier to contain Yajuj and Majuj?", "Dhul-Qarnayn"],
    ["Which idol did the people of Ilyas (AS) worship?", "Ba'al"],
    ["How many Sahabi fought in the Battle of Badr?", "313"],
    ["How many angels will be holding down Jahannam on the Day of Qiyamah?", "4.9 Billion"],
    ["Who will blow the trumpet on the Day of Qiyamah?", "Israfil (As)"],
    ["Which Surah is called 'The Protector' against punishment of the grave?", "Surah Al-Mulk"], 
    ["How many juzz are there in the Quran?", "30"],
    ["Which Surah discusses the Battle of Badr?", "Surah Al-Anfal"],
    ["What is the name of Ibrahim (As)'s father?", "Azar"],
    ["How many daughters did Prophet Muhammad (ﷺ) have?", "4"],
    ["What was the second battle of Islam?", "Battle of Uhud"],
    ["How many wives did Prophet Muhammad (ﷺ) have?", "11"],
    ["Which angel brought revelation to the prophets?", "Jibrael (As)"],
    ["Who was the first wife of Prophet Muhammad (ﷺ)?", "Khadijah bint Khuwaylid (Ra)"],
    ["Which Surah is known as 'Umm al-Quran'?", "Surah Al-Fatiha"],
    ["Which prophet was given the Zabur?", "Dawud (As)"],
    ["Which nation was given a she-camel as a sign from Allah?", "Thamud"],
    ["Who was the companion known as 'Al-Amin'?", "Abu Ubaidah ibn al-Jarrah (Ra)"],
    ["Which prophet was given the ability to control the wind?", "Prophet Sulaiman (As)"],
    ["Who was the first mu'azzin in Islam?", "Bilal ibn Rabah (Ra)"],
    ["Which prophet was the grandson of Ibrahim (As)", "Ishaq (As)"],
    ["Which Surah was revealed completely in one night?", "Surah Al-An'am"],
    ["Which companion was known as 'As-Siddiq'?", "Abu Bakr (RA)"],
    ["What was the first battle of Islam?", "Battle of Badr"],
    ["Which prophet's people were destroyed by a rain of stones?", "Prophet Lut (As)"],
    ["Which prophet had the miracle of reviving the dead by Allah's permission?", "I'sa (As)"],
    ["How many Sahabas were given the news of Jannah in their lifetime?", "10"],
    ["Which prophet is known as Israel?", "Yaqub (As)"],
    ["Who was the prophet thrown into a well by his brothers?", "Yusuf (As)"],
    ["Who was the great-grandson of Ibrahim (As)?", "Yusuf (As)"],
    ["Who was the king that opposed Ibrahim (As)?", "Namrud"],
    ["Which prophet was sent to the people of 'Ad?", "Hud (As)"],
    ["Which prophet's nation was destroyed for the practice of homosexuality?", "Lut (As)"],
    ["Who was the son of Ibrahim (As) and Sarah (As)?", "Ishaq (As)"],
    ["Who defeated Jalut (Goliath) with a sling?", "Dawud (As)"],
    ["Which queen visited Sulaiman (As) and accepted Islam?", "Queen of Sheba (Bilqis)"],
    ["Who was the wife of Adam (As)?", "Hawa (As)"],
    ["Which prophet was sent to the people of Thamud?", "Salih (As)"],
    ["Which prophet spoke to Allah directly?", "Musa (As)"],
    ["Which prophet was tested with the command to sacrifice his son?", "Ibrahim (As)"],
    ["Who was the son of Ibrahim (As) and Hajar (As)?", "Ismael (As)"],
    ["Which prophet was sent to the people of Madyan?", "Shuaib (As)"],
    ["Who was the father-in-law of Musa (As)?", "Shuaib (As)"],
    ["Which prophet was given the Torah?", "Musa (As)"],
    ["Who was the brother and helper of Musa (As)?", "Harun (As)"],
    ["Who was the father of Sulaiman (As)?", "Dawud (As)"],
    ["Which prophet could understand the language of animals and jinn?", "Sulaiman (As)"],
    ["Who was the son of Dawud (As)?", "Sulaiman (As)"],
    ["Who was the queen that ruled during the time of Sulaiman (As)?", "Queen of Sheba (Bilqis)"],
    ["Which prophet was sent to the people who worshipped the idol Ba'al?", "Ilyas (As)"],
    ["Who is also known as 'Dhun-Nun'?", "Yunus (As)\n(the one of the fish)"],
    ["Which prophet was the guardian of Maryam (As)?", "Zakariya (As)"],
    ["Who was the father of Yahya (As)?", "Zakariya (As)"],
    ["Which prophet was the son of Zakariya (As)?", "Yahya (As)"],
    ["Which prophet was born without a father?", "Isa (As)"],
    ["Who is referred to as Al-Masih in the Quran?", "Isa (As)"],
    ["Which prophet was given the Injil (Gospel)?", "Isa (As)"],
    ["Which prophet will return before the day of Qiyamah?", "Isa (As)"],
    ["Which prophet received the Quran?", "Muhammad (ﷺ)"],
    ["Give me a Surah that starts with the letter 'S'", "Surah Sad / Saffat / Shura"],
    ["Give me a Surah that starts with the letter 'T'", "Surah Tawba / Ta-Ha / Tin"],
    ["Give me a Surah that starts with the letter 'Y'", "Surah Yusuf / Yunus / Yaseen"],
    ["Give me a Surah that starts with the letter 'A'", "Surah A'raf / Ahzab / A'basa"],
    ["Give me a Surah that starts with the letter 'M'", "Surah Maryam / Muhammad / Mulk"],
    ["Give me a Surah that starts with the letter 'K'", "Surah Kahf / Kafirun / Kawthar"],
    ["Give me a Surah that starts with the letter 'N'", "Surah Nisa / Nur / Naas"],
    ["Give me a Surah that starts with the letter 'Z'", "Surah Zumar / Zukhruf / Zalzalah"],
    ["Give me a Surah that starts with the letter 'D'", "Surah Dhukhan / Dhuha"],
    ["Give me a Surah that starts with the letter 'F'", "Surah Fussilat / Furqan / Fath"],
    ["Give me a Surah that starts with the letter 'B'", "Surah Baqara / Buruj / Bayyina"],
    ["Give me a Surah that starts with the letter 'I'", "Surah Ibrahim / Insaan / Inshiqaq"],
    ["Who was the first caliph of Islam?", "Abu Bakr As-Siddiq (Ra)"],
    ["Who was the second caliph of Islam?", "Umar ibn Al-Khattab (Ra)"],
    ["Who was the third caliph of Islam?", "Uthman ibn Affan (Ra)"],
    ["Who was the fourth caliph of Islam?", "Ali ibn Abi Talib (Ra)"],
    ["Who was the owner of Bilal ibn Rabah (RA) before his salvation?", "Umayyah ibn Khalaf"],    
    ["What was the actual name of Abu Jahl?", "Amr ibn Hisham"],
    ["In which battle did Abu Jahl die?", "Battle of Badr"],
    ["Who led the Battle of Badr from the disbelievers' side?", "Abu Jahl"],
    ["Who led the Battle of Uhud from the disbelievers' side?", "Abu Sufyan ibn Harb"],
    ["Which uncle of the Prophet (ﷺ) is cursed in the Quran?", "Abu Lahab"],
    ["Who is known as the 'carrier of firewood'?", "Umm Jamil (Wife of Abu Lahab)"],
    ["How many years did it take for the Quran to be revealed?", "23 years"],
    ["How many gates does Jannah have?", "8"],
    ["What is the name of the gate of Paradise for those who fasted?", "Ar-Rayyan"],
    ["What is the name of the gate of Paradise for those who prayed regularly?", "Bab us-Salah"],
    ["What is the name of the gate of Paradise for those who fought in Jihad?", "Bab ul-Jihad"],
    ["What is the name of the gate of Paradise for those who gave charity?", "Bab us-Sadaqah"],
    ["How many gates does Jahannam have?", "7"],
    ["What is the name of the deepest level of Jahannam?", "Al-Hawiyah"],
    ["Who is the keeper of Jahannam?", "Malik (As)"],
    ["What is the tree in Jahannam called?", "Zaqqum"],
    ["What is the highest level of Jannah called?", "Al-Firdaus"],
    ["What is the name of the river in Jannah from which other rivers flow?", "Al-Kawthar"],
    ["What is the name of the tree in Jannah whose shade lasts for more than 100 years?", "Tuba"],
    ["What are the four types of rivers in Jannah?", "Water, Milk, Honey, & Wine"],
    ["How many levels of beauty do Al-Hoor have?", "70 levels of beauty"],
    ["What will be the smell of the sweat of the dwellers of Jannah?", "Musk"],
    ["Prophet Muhammad (ﷺ) said that the fever is the heat from what?", "Hell Fire"],

];
