final List<List<String>> questionAnswer = [
    ["Who is known as 'Dhul-Nurayn'?", "Uthman ibn Affan (RA)"],
    ["Which prophet was swallowed by a big fish?", "Prophet Yunus (AS)"],
    ["Which Surah has only 3 verses?", "Surah Al-Kawthar"],
    ["What is the first word revealed in the Qur'an?", "Iqra (Read)"],
    ["Who was the first child to accept Islam?", "Ali ibn Abi Talib (RA)"],
    ["Which prophet had a father and grandfather who were prophets?", "Prophet Yusuf (AS)"],
    ["Who is the last prophet in Islam?", "Prophet Muhammad (SAW)"],
    ["Which prophet is known for building the Ark?", "Prophet Nuh (AS)"],
    ["Which prophet was thrown into the fire but was saved by Allah?", "Prophet Ibrahim (AS)"],
    ["Who was the mother of Prophet Isa (AS)?", "Maryam (AS)"],
    ["Which prophet split the sea with Allah's permission?", "Prophet Musa (AS)"],
    ["Which Surah is known as 'The Heart of the Qur'an'?", "Surah Yasin"],
    ["Who was the companion known as 'The Sword of Allah'?", "Khalid ibn Al-Walid (RA)"],
    ["Which prophet interpreted the king's dream in Egypt?", "Prophet Yusuf (AS)"],
    ["Which prophet is mentioned most frequently in the Qur'an?", "Prophet Musa (AS)"],
    ["Who was the wife of Prophet Ibrahim (AS)?", "Sarah (AS)"],
    ["Which prophet prayed for the rain in drought?", "Prophet Nuh (AS)"],
    ["Which Surah is named after a woman?", "Surah Maryam"],
    ["Who is the first prophet according to Islamic teachings?", "Prophet Adam (AS)"],
    ["Which companion was known for his knowledge and wisdom?", "Abu Hurairah (RA)"],
    ["Who was the first martyr in Islam?", "Sumayyah bint Khayyat (RA)"],
    ["Which prophet was known for his patience?", "Prophet Ayyub (AS)"],
    ["Which prophet talked to ants?", "Prophet Sulaiman (AS)"],
    ["Who is known as 'Al-Faruq' among the companions?", "Umar ibn Al-Khattab (RA)"],
    ["Which prophet's story includes a well and a basket?", "Prophet Musa (AS)"],
];
