class UserInfoModel {
  final String name;
  final int score;
  final String badge;

  UserInfoModel({
    required this.name,
    required this.score,
    required this.badge,
  });
}

// Dummy list of users (80 Muslim names)
final List<UserInfoModel> dummyUsers = [
    UserInfoModel(name: "Abdullah", score: 15100, badge: "Diamond"),
    UserInfoModel(name: "Abdur Rahman", score: 12000, badge: "Sapphire"),
    UserInfoModel(name: "Abu Bakr", score: 9800, badge: "Ruby"),
    UserInfoModel(name: "Umar", score: 8900, badge: "Emerald"),
    UserInfoModel(name: "Uthman", score: 7500, badge: "Emerald"),
    UserInfoModel(name: "Ali", score: 7000, badge: "Ruby"),
    UserInfoModel(name: "Talha", score: 6800, badge: "Ruby"),
    UserInfoModel(name: "Zubair", score: 6600, badge: "Ruby"),
    UserInfoModel(name: "Bilal", score: 6400, badge: "Emerald"),
    UserInfoModel(name: "Khalid", score: 6000, badge: "Emerald"),
    UserInfoModel(name: "Saad", score: 5800, badge: "Gold"),
    UserInfoModel(name: "Salman", score: 5600, badge: "Gold"),
    UserInfoModel(name: "Ammar", score: 5400, badge: "Gold"),
    UserInfoModel(name: "Hudhaifah", score: 5200, badge: "Gold"),
    UserInfoModel(name: "Abu Hurairah", score: 5000, badge: "Tanzanite"),
    UserInfoModel(name: "Muawiyah", score: 4800, badge: "Tanzanite"),
    UserInfoModel(name: "Yahya", score: 4600, badge: "Tanzanite"),
    UserInfoModel(name: "Ibrahim", score: 4400, badge: "Garnet"),
    UserInfoModel(name: "Ismail", score: 4200, badge: "Garnet"),
    UserInfoModel(name: "Ishaq", score: 4000, badge: "Garnet"),
    UserInfoModel(name: "Yaqub", score: 3800, badge: "Amethyst"),
    UserInfoModel(name: "Yusuf", score: 3600, badge: "Amethyst"),
    UserInfoModel(name: "Musa", score: 3400, badge: "Amethyst"),
    UserInfoModel(name: "Harun", score: 3200, badge: "Amber"),
    UserInfoModel(name: "Dawud", score: 3000, badge: "Amber"),
    UserInfoModel(name: "Sulaiman", score: 2800, badge: "Amber"),
    UserInfoModel(name: "Ayub", score: 2600, badge: "Bronzite"),
    UserInfoModel(name: "Yunus", score: 2400, badge: "Bronzite"),
    UserInfoModel(name: "Zakariya", score: 2200, badge: "Bronzite"),
    UserInfoModel(name: "Idris", score: 2000, badge: "Amber"),
    UserInfoModel(name: "Shuayb", score: 1800, badge: "Amber"),
    UserInfoModel(name: "Ilyas", score: 1600, badge: "Amber"),
    UserInfoModel(name: "Lut", score: 1400, badge: "Bronzite"),
    UserInfoModel(name: "Nuh", score: 1200, badge: "Bronzite"),
    UserInfoModel(name: "Adam", score: 1000, badge: "No Badge"),
    UserInfoModel(name: "Muhammad", score: 20000, badge: "Diamond"),
    UserInfoModel(name: "Hasan", score: 18500, badge: "Diamond"),
    UserInfoModel(name: "Husayn", score: 18200, badge: "Diamond"),
    UserInfoModel(name: "Jaafar", score: 17800, badge: "Diamond"),
    UserInfoModel(name: "Anas", score: 17500, badge: "Diamond"),
    UserInfoModel(name: "Ikrimah", score: 17200, badge: "Diamond"),
    UserInfoModel(name: "Saib", score: 16900, badge: "Sapphire"),
    UserInfoModel(name: "Abbas", score: 16600, badge: "Sapphire"),
    UserInfoModel(name: "Hamzah", score: 16200, badge: "Sapphire"),
    UserInfoModel(name: "Ubaydah", score: 15800, badge: "Sapphire"),
    UserInfoModel(name: "Thabit", score: 15500, badge: "Ruby"),
    UserInfoModel(name: "Aqil", score: 15200, badge: "Ruby"),
    UserInfoModel(name: "Nuaym", score: 15000, badge: "Ruby"),
    UserInfoModel(name: "Suhayb", score: 14800, badge: "Emerald"),
    UserInfoModel(name: "Miqdad", score: 14600, badge: "Emerald"),
    UserInfoModel(name: "Hudhayfah", score: 14400, badge: "Emerald"),
    UserInfoModel(name: "Abd alAziz", score: 14200, badge: "Emerald"),
    UserInfoModel(name: "Owais", score: 14000, badge: "Gold"),
    UserInfoModel(name: "Saifullah", score: 13800, badge: "Gold"),
    UserInfoModel(name: "Usayd", score: 13600, badge: "Gold"),
    UserInfoModel(name: "Musab", score: 13400, badge: "Gold"),
    UserInfoModel(name: "Qasim", score: 13200, badge: "Tanzanite"),
    UserInfoModel(name: "Barakah", score: 13000, badge: "Tanzanite"),
    UserInfoModel(name: "Safwan", score: 12800, badge: "Tanzanite"),
    UserInfoModel(name: "Tamim", score: 12600, badge: "Garnet"),
    UserInfoModel(name: "Zayd", score: 12400, badge: "Garnet"),
    UserInfoModel(name: "Fadl", score: 12200, badge: "Garnet"),
    UserInfoModel(name: "Rafi", score: 12000, badge: "Amethyst"),
    UserInfoModel(name: "Nafi", score: 11800, badge: "Amethyst"),
    UserInfoModel(name: "Sahl", score: 11600, badge: "Amethyst"),
    UserInfoModel(name: "Thalhah", score: 11400, badge: "Amber"),
    UserInfoModel(name: "Umair", score: 11200, badge: "Amber"),
    UserInfoModel(name: "Hanzalah", score: 11000, badge: "Amber"),
    UserInfoModel(name: "Harith", score: 10800, badge: "Bronzite"),
    UserInfoModel(name: "Mujahid", score: 10600, badge: "Bronzite"),
    UserInfoModel(name: "Sakhr", score: 10400, badge: "Bronzite"),
    UserInfoModel(name: "Ayman", score: 10200, badge: "Bronzite"),
    UserInfoModel(name: "Furqan", score: 10000, badge: "Bronzite"),
    UserInfoModel(name: "Ibn Abbas", score: 9800, badge: "Ruby"),
    UserInfoModel(name: "Ibn Umar", score: 9600, badge: "Ruby"),
    UserInfoModel(name: "Ibn Masud", score: 9400, badge: "Ruby"),
    UserInfoModel(name: "Abu Talib", score: 9200, badge: "Emerald"),
];
