class UserInfoModel {
    final String name;
    final int score;

    UserInfoModel({
        required this.name,
        required this.score,
    });
}

// Dummy list of users (80 Muslim names)
final List<UserInfoModel> dummyUsers = [
    UserInfoModel(name: "Abdullah", score: 15100),
    UserInfoModel(name: "Abdur Rahman", score: 12000),
    UserInfoModel(name: "Abu Bakr", score: 9800),
    UserInfoModel(name: "Umar", score: 8900),
    UserInfoModel(name: "Uthman", score: 7500),
    UserInfoModel(name: "Ali", score: 7000),
    UserInfoModel(name: "Talha", score: 6800),
    UserInfoModel(name: "Zubair", score: 6600),
    UserInfoModel(name: "Bilal", score: 6400),
    UserInfoModel(name: "Khalid", score: 6000),
    UserInfoModel(name: "Saad", score: 5800),
    UserInfoModel(name: "Salman", score: 5600),
    UserInfoModel(name: "Ammar", score: 5400),
    UserInfoModel(name: "Hudhaifah", score: 5200),
    UserInfoModel(name: "Abu Hurairah", score: 5000),
    UserInfoModel(name: "Muawiyah", score: 4800),
    UserInfoModel(name: "Yahya", score: 4600),
    UserInfoModel(name: "Ibrahim", score: 4400),
    UserInfoModel(name: "Ismail", score: 4200),
    UserInfoModel(name: "Ishaq", score: 4000),
    UserInfoModel(name: "Yaqub", score: 3800),
    UserInfoModel(name: "Yusuf", score: 3600),
    UserInfoModel(name: "Musa", score: 3400),
    UserInfoModel(name: "Harun", score: 3200),
    UserInfoModel(name: "Dawud", score: 3000),
    UserInfoModel(name: "Sulaiman", score: 2800),
    UserInfoModel(name: "Ayub", score: 2600),
    UserInfoModel(name: "Yunus", score: 2400),
    UserInfoModel(name: "Zakariya", score: 2200),
    UserInfoModel(name: "Idris", score: 2000),
    UserInfoModel(name: "Shuayb", score: 1800),
    UserInfoModel(name: "Ilyas", score: 1600),
    UserInfoModel(name: "Lut", score: 1400),
    UserInfoModel(name: "Nuh", score: 1200),
    UserInfoModel(name: "Adam", score: 1000),
    UserInfoModel(name: "Muhammad", score: 20000),
    UserInfoModel(name: "Hasan", score: 18500),
    UserInfoModel(name: "Husayn", score: 18200),
    UserInfoModel(name: "Jaafar", score: 17800),
    UserInfoModel(name: "Anas", score: 17500),
    UserInfoModel(name: "Ikrimah", score: 17200),
    UserInfoModel(name: "Saib", score: 16900),
    UserInfoModel(name: "Abbas", score: 16600),
    UserInfoModel(name: "Hamzah", score: 16200),
    UserInfoModel(name: "Ubaydah", score: 15800),
    UserInfoModel(name: "Thabit", score: 15500),
    UserInfoModel(name: "Aqil", score: 15200),
    UserInfoModel(name: "Nuaym", score: 15000),
    UserInfoModel(name: "Suhayb", score: 14800),
    UserInfoModel(name: "Miqdad", score: 14600),
    UserInfoModel(name: "Hudhayfah", score: 14400),
    UserInfoModel(name: "Abd alAziz", score: 14200),
    UserInfoModel(name: "Owais", score: 14000),
    UserInfoModel(name: "Saifullah", score: 13800),
    UserInfoModel(name: "Usayd", score: 13600),
    UserInfoModel(name: "Musab", score: 13400),
    UserInfoModel(name: "Qasim", score: 13200),
    UserInfoModel(name: "Barakah", score: 13000),
    UserInfoModel(name: "Safwan", score: 12800),
    UserInfoModel(name: "Tamim", score: 12600),
    UserInfoModel(name: "Zayd", score: 12400),
    UserInfoModel(name: "Fadl", score: 12200),
    UserInfoModel(name: "Rafi", score: 12000),
    UserInfoModel(name: "Nafi", score: 11800),
    UserInfoModel(name: "Sahl", score: 11600),
    UserInfoModel(name: "Thalhah", score: 11400),
    UserInfoModel(name: "Umair", score: 11200),
    UserInfoModel(name: "Hanzalah", score: 11000),
    UserInfoModel(name: "Harith", score: 10800),
    UserInfoModel(name: "Mujahid", score: 10600),
    UserInfoModel(name: "Sakhr", score: 10400),
    UserInfoModel(name: "Ayman", score: 12000),
    UserInfoModel(name: "Furqan", score: 10000),
    UserInfoModel(name: "Ibn Abbas", score: 8000),
    UserInfoModel(name: "Ibn Umar", score: 5000),
    UserInfoModel(name: "Ibn Masud", score: 3500),
    UserInfoModel(name: "Musab ibn Umayr", score: 2500),
    UserInfoModel(name: "Thalaba", score: 1200),
    UserInfoModel(name: "Yusuf ibn Yaqub", score: 700),
    UserInfoModel(name: "Ibrahim", score: 400),
    UserInfoModel(name: "Yasin", score: 150),
    UserInfoModel(name: "Tasin", score: 20),
];
